version: '3.4'

services: 
    db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - "1469:1433"
      environment:
        SA_PASSWORD: "Numsey@Password!"
        ACCEPT_EULA: "Y"
    
    redis:
      image: redis:latest
      ports:
        - "1402:6379"